export const SAVE_ADDRESS = 'save_address'
export const SAVE_CATEGORY = 'save_category'
export const SAVE_SHOPLIST = 'save_shopList'
export const SAVE_USERINFO = 'save_userInfo'
export const SAVE_TOKEN = 'save_token'